### PR TITLE
get_map now accepts more generic SS_List instead of DataList

### PR DESCRIPTION
**Pull request by wernerkrauss**
This enables us to decorate ArrayList with Mappable

### CODE REVIEW

**Comment by gordonbanderson** [comment]
Thanks for the pull request, and good to know people are using the module :)

**Comment by wernerkrauss** [comment]
It's the most up to date version of the module... any chance you can merge back your work to the "official" module?

**Comment by gordonbanderson** [comment]
Which one is the "official" module, I note Uncle Cheese's has not been updated since 2011 https://github.com/unclecheese/Mappable - is this the one you are referring to?

**Comment by wernerkrauss** [comment]
yup. unclecheese's original module which is known best. maybe you can take it over or merge back? dunno.

**Comment by wernerkrauss** [comment]
or maybe he can note for updaters that your module is up to date and has additional features. maybe with some kind of upgrade path, though updating my current 2.4 -> 3.1project was quite easy.

**Pull request merged**
